services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

  dynamodb-tools:
    build:
      context: .
      target: runtime
    ports:
      - "127.0.0.1:8002:80"
    environment:
      DATA_PATH: /examples/basic
    depends_on:
      - dynamodb
    restart: on-failure
